builds:
  - binary: terraform-provider-dspc
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

signs:
  - artifacts: checksum
    signature: "${artifact}.sig"
    cmd: gpg
    args:
      - "--batch"
      - "--yes"
      - "--passphrase-fd"
      - "0"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--detach-sign"
      - "--armor"
      - "--output"
      - "${signature}"
      - "${artifact}"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'