# Terraform Provider Release Configuration
before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    binary: terraform-provider-dspc
    ldflags:
      - -s -w

archives:
  - format: zip
    name_template: >-
      terraform-provider-dspc_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if eq .Os "windows" }}.exe{{ end }}

checksum:
  name_template: 'terraform-provider-dspc_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    signature: terraform-provider-dspc_{{ .Version }}_SHA256SUMS.sig

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: NL-AMS-DSPC
    name: terraform-provider-dspc
  draft: false
  prerelease: false
  mode: replace
  name_template: "{{ .ProjectName }} {{ .Version }}"
  header: |
    ## Release {{ .Version }}

    See the [CHANGELOG.md](CHANGELOG.md) for details.

  footer: |
    ## Installation

    ### Terraform Registry

    ```hcl
    terraform {
      required_providers {
        dspc = {
          source  = "NL-AMS-DSPC/dspc"
          version = "~> {{ .Version }}"
        }
      }
    }
    ```

    ### Manual Installation

    1. Download the appropriate binary for your platform from the assets below
    2. Place it in your Terraform plugins directory:
       - **Windows**: `%APPDATA%\terraform.d\plugins\registry.terraform.io\NL-AMS-DSPC\dspc\{{ .Version }}\windows_amd64\`
       - **macOS**: `~/.terraform.d/plugins/registry.terraform.io/NL-AMS-DSPC/dspc/{{ .Version }}/darwin_amd64/`
       - **Linux**: `~/.terraform.d/plugins/registry.terraform.io/NL-AMS-DSPC/dspc/{{ .Version }}/linux_amd64/`
    3. Rename the binary to `terraform-provider-dspc` (add `.exe` extension on Windows)

    ## Documentation

    Full documentation is available at: https://registry.terraform.io/providers/NL-AMS-DSPC/dspc/latest/docs
